# Generated by Django 2.2.6 on 2019-11-02 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('school_id', models.CharField(max_length=50)),
                ('propix', models.ImageField(blank=True, null=True, upload_to='pictures')),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('time_start', models.TimeField(null=True)),
                ('time_end', models.TimeField(null=True)),
                ('days', models.CharField(max_length=10)),
                ('date_start', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
                ('year_start', models.CharField(max_length=4)),
                ('year_end', models.CharField(max_length=4)),
                ('semester', models.CharField(choices=[('SUMMER', 'Summer'), ('SECOND', '2nd Semeseter'), ('FIRST', '1st Semester')], default='1st Semester', max_length=25)),
                ('headerpix', models.ImageField(blank=True, null=True, upload_to='pictures')),
            ],
            options={
                'db_table': 'Classroom',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ADMIN', 'Admin'), ('PROFESSOR', 'Professor'), ('STUDENT', 'Student')], default='Student', max_length=50)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('classroom', models.ManyToManyField(blank=True, to='app.Classroom')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('classroom', models.ManyToManyField(blank=True, to='app.Classroom')),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, max_length=1024, null=True)),
                ('date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Classroom')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messege', models.CharField(max_length=512)),
                ('date', models.DateTimeField()),
                ('messagetoandfrom', models.ManyToManyField(blank=True, to='app.Account')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileloc', models.FileField(blank=True, null=True, upload_to='media')),
                ('date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Classroom')),
            ],
            options={
                'db_table': 'lecture',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('color', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Classroom')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Login'),
        ),
    ]
