# Generated by Django 2.2.6 on 2019-11-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191102_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('SECOND', '2nd Semeseter'), ('SUMMER', 'Summer'), ('FIRST', '1st Semester')], default='1st Semester', max_length=25),
        ),
        migrations.AlterField(
            model_name='login',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
