# Generated by Django 2.2.6 on 2019-11-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191102_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='headerpix',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('SUMMER', 'Summer'), ('SECOND', '2nd Semeseter'), ('FIRST', '1st Semester')], default='1st Semester', max_length=25),
        ),
    ]
