# Generated by Django 2.2.6 on 2019-11-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191103_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('SECOND', '2nd Semeseter'), ('SUMMER', 'Summer'), ('FIRST', '1st Semester')], default='1st Semester', max_length=25),
        ),
    ]
