# Generated by Django 2.2.6 on 2019-11-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191104_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='year_end',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='year_start',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('SUMMER', 'Summer'), ('SECOND', '2nd Semeseter'), ('FIRST', '1st Semester')], default='1st Semester', max_length=25),
        ),
    ]
