# Generated by Django 2.2.6 on 2019-11-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191104_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='headerpix',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='invite_token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('FIRST', '1st Semester'), ('SUMMER', 'Summer'), ('SECOND', '2nd Semeseter')], default='1st Semester', max_length=25),
        ),
    ]
