# Generated by Django 2.2.6 on 2019-11-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191104_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='downvoted_post',
            field=models.ManyToManyField(blank=True, related_name='downvoted_post_prof', to='app.Post'),
        ),
        migrations.AddField(
            model_name='professor',
            name='upvoted_post',
            field=models.ManyToManyField(blank=True, related_name='upvoted_post_prof', to='app.Post'),
        ),
        migrations.AddField(
            model_name='student',
            name='downvoted_post',
            field=models.ManyToManyField(blank=True, related_name='downvoted_post_stud', to='app.Post'),
        ),
        migrations.AddField(
            model_name='student',
            name='upvoted_post',
            field=models.ManyToManyField(blank=True, related_name='upvoted_post_stud', to='app.Post'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('SECOND', '2nd Semeseter'), ('SUMMER', 'Summer'), ('FIRST', '1st Semester')], default='1st Semester', max_length=25),
        ),
    ]
