# Generated by Django 2.2.6 on 2019-11-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20191110_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='lecture_no',
            new_name='no',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='lecture_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('FIRST', '1st Semester'), ('SECOND', '2nd Semeseter'), ('SUMMER', 'Summer')], default='1st Semester', max_length=25),
        ),
    ]
