# Generated by Django 2.2.6 on 2019-11-12 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20191112_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='messagetoandfrom',
        ),
        migrations.RemoveField(
            model_name='message',
            name='messege',
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to='app.Account'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to='app.Account'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('FIRST', '1st Semester'), ('SUMMER', 'Summer'), ('SECOND', '2nd Semeseter')], default='1st Semester', max_length=25),
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
