# Generated by Django 2.2.6 on 2019-11-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191112_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('FIRST', '1st Semester'), ('SECOND', '2nd Semeseter'), ('SUMMER', 'Summer')], default='1st Semester', max_length=25),
        ),
    ]
